### PR TITLE
[KIECLOUD-332] image naming convention changes

### PR DESCRIPTION
**Pull request by errantepiphany**
[KIECLOUD-332] image naming convention changes
https://issues.jboss.org/browse/KIECLOUD-332

Signed-off-by: David Ward <dward@redhat.com>

### CODE REVIEW

**Review by ruromero — APPROVED** [review]
That one was easy to review

**Comment by spolti** [comment]
does it needs to be deleted?
Or can't we just let it here and update the README?

**Comment by ruromero** [comment]
@spolti as we keep the tags, that should help users understand it is not under development anymore

**Comment by spolti** [comment]
Sounds good, however, @errantepiphany can you add on the README telling users that for old versions they can check the tags/branches?

**Comment by errantepiphany** [comment]
> Sounds good, however, @errantepiphany can you add on the README a message telling users that for old versions they can check the tags/branches?

@spolti Done. Please see the updated README.

**Review by spolti — APPROVED** [review]

**Pull request merged**
